# Offense count: 55
# Configuration parameters: AllowedMethods.
# AllowedMethods: enums
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'test/child_killing_test.rb'
    - 'test/forking_test.rb'
    - 'test/job_hooks_test.rb'
    - 'test/job_plugins_test.rb'
    - 'test/plugin_test.rb'
    - 'test/worker_test.rb'

# Offense count: 7
Lint/RescueException:
  Exclude:
    - 'test/rake_test.rb'
    - 'test/worker_test.rb'

# Offense count: 1
Lint/UnreachableCode:
  Exclude:
    - 'test/job_hooks_test.rb'

# Offense count: 2
Lint/UnreachableLoop:
  Exclude:
    - 'test/resque_failure_multi_queue_test.rb'
    - 'test/resque_failure_redis_test.rb'

# Offense count: 5
Lint/UselessAssignment:
  Exclude:
    - 'test/resque_failure_multi_queue_test.rb'
    - 'test/worker_test.rb'

# Offense count: 60
# Configuration parameters: EnforcedStyle.
# SupportedStyles: snake_case, camelCase
Naming/VariableName:
  Exclude:
    - 'test/worker_manager_test.rb'

# Offense count: 1
Security/MarshalLoad:
  Exclude:
    - 'test/worker_test.rb'
